# Generated by Django 2.1.2 on 2018-10-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_auto_20181012_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='dt_criacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
